import type { PetTheme, ThemeId } from '~/types/pet'

export const DEFAULT_THEME_ID: ThemeId = 'default'

export const PET_THEMES: PetTheme[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Clean workday colors with warm pet accents.',
    premium: false,
    colors: {
      background: '#f6f7f9',
      surface: '#ffffff',
      surfaceStrong: '#eef1f5',
      border: '#d9dee7',
      text: '#20242c',
      muted: '#697282',
      accent: '#246bfe',
      accentText: '#ffffff',
      warning: '#b45309',
      success: '#047857',
      petBase: '#f3b15f',
      petContrast: '#2f241b',
    },
    statusColors: {
      happy: '#f3b15f',
      hungry: '#eab308',
      sleepy: '#60a5fa',
      bored: '#94a3b8',
      sad: '#a78bfa',
      excited: '#22c55e',
    },
  },
  {
    id: 'focus',
    name: 'Focus',
    description: 'Muted office palette for quiet desks.',
    premium: false,
    colors: {
      background: '#f3f4f1',
      surface: '#ffffff',
      surfaceStrong: '#e5e8df',
      border: '#d5d9cd',
      text: '#252820',
      muted: '#6f7664',
      accent: '#3f6f4f',
      accentText: '#ffffff',
      warning: '#a16207',
      success: '#166534',
      petBase: '#d4a373',
      petContrast: '#2d241b',
    },
    statusColors: {
      happy: '#d4a373',
      hungry: '#ca8a04',
      sleepy: '#4f8fb8',
      bored: '#8a9381',
      sad: '#8b6f9f',
      excited: '#4d8b5f',
    },
  },
  {
    id: 'night',
    name: 'Night',
    description: 'Dark workspace with high contrast controls.',
    premium: false,
    colors: {
      background: '#14161a',
      surface: '#1f2329',
      surfaceStrong: '#2a3038',
      border: '#3a424d',
      text: '#f1f5f9',
      muted: '#a8b2c1',
      accent: '#38bdf8',
      accentText: '#07131d',
      warning: '#f59e0b',
      success: '#34d399',
      petBase: '#c084fc',
      petContrast: '#111827',
    },
    statusColors: {
      happy: '#c084fc',
      hungry: '#facc15',
      sleepy: '#38bdf8',
      bored: '#64748b',
      sad: '#818cf8',
      excited: '#2dd4bf',
    },
  },
  {
    id: 'pastel',
    name: 'Pastel',
    description: 'Soft color set reserved for premium skins.',
    premium: true,
    colors: {
      background: '#fbf7f3',
      surface: '#ffffff',
      surfaceStrong: '#f5ebe0',
      border: '#e7d8ca',
      text: '#2b2723',
      muted: '#7a6f66',
      accent: '#d97757',
      accentText: '#ffffff',
      warning: '#b45309',
      success: '#0f766e',
      petBase: '#f5a3b7',
      petContrast: '#3b2028',
    },
    statusColors: {
      happy: '#f5a3b7',
      hungry: '#f0b85a',
      sleepy: '#8ecae6',
      bored: '#b7b7a4',
      sad: '#b8a1d9',
      excited: '#84cc9a',
    },
  },
]
