// Toolbar popup: see the pet, care for it, or move it between the website and the extension.
import { DEFAULT_PET_NAMES } from '~/constants/pet'
import type { PetAction, PetSpecies, PetState } from '~/types/pet'
import { renderPetArtSvg } from '~/utils/petArt'
import { decodePetBackupWithPurchases, encodePetBackup } from '~/utils/petBackup'
import { getActiveStreak } from '~/utils/petStreak'
import { pickVoiceLine } from '~/utils/petVoice'
import { getMessages } from './messages'
import { adoptPet, careFor, loadPet, remainingCare, serializePet, statusOf } from './petCore'
import { NOTIFY_KEY, PET_KEY, readStorage, writeStorage } from './storage'

const SPECIES: PetSpecies[] = ['cat', 'dog', 'hedgehog', 'rabbit', 'penguin', 'hamster']
const ACTIONS: PetAction[] = ['feed', 'play', 'sleep', 'wash']
const ACTION_ICONS: Record<PetAction, string> = {
  feed: '<path d="M5 15h22c0 6.5-4.9 11-11 11S5 21.5 5 15Z" fill="#ffe2bf"/><path d="M11 11c0-2 2-2 2-4M16 11c0-2 2-2 2-4M21 11c0-2 2-2 2-4"/>',
  play: '<circle cx="16" cy="16" r="10" fill="#ffd0cb"/><path d="M7 12.5c6 2 12 2 18 0M7.5 20c5.5-2 11.5-2 17 0"/>',
  sleep: '<path d="M24 20.5A10 10 0 0 1 12 7a10 10 0 1 0 12 13.5Z" fill="#dbe4f7"/><path d="M20 6h4l-4 4h4"/>',
  wash: '<path d="M16 4c4.5 6 8 10 8 14a8 8 0 0 1-16 0c0-4 3.5-8 8-14Z" fill="#cdeeea"/><path d="M12.5 18.5a3.5 3.5 0 0 0 3.5 3.5"/>',
}

const messages = getMessages()
const root = document.getElementById('app')!
let pet: PetState | null = null
let flashLine = ''
let flashTimer: ReturnType<typeof setTimeout> | null = null

void start()

async function start(): Promise<void> {
  pet = loadPet(await readStorage(PET_KEY), Date.now())
  if (pet) await save()
  render()
}

async function save(): Promise<void> {
  if (pet) await writeStorage({ [PET_KEY]: serializePet(pet) })
}

function render(): void {
  root.replaceChildren(pet ? renderPet(pet) : renderAdoption())
}

function el<K extends keyof HTMLElementTagNameMap>(tag: K, className = '', text = ''): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag)
  if (className) node.className = className
  if (text) node.textContent = text

  return node
}

function art(svg: string, className: string): HTMLElement {
  const holder = el('span', className)
  holder.innerHTML = svg // Generated by our own renderer, never user input.

  return holder
}

function renderPet(state: PetState): HTMLElement {
  const now = Date.now()
  const status = statusOf(state, now)
  const view = el('div', 'pet')

  const hero = el('div', 'pet__hero')
  hero.append(art(renderPetArtSvg({ species: state.species, status, idPrefix: 'popup' }), 'pet__art'))
  const heading = el('div', 'pet__heading')
  const name = el('strong', 'pet__name', state.name)
  const mood = el('span', 'pet__mood', messages.status.labels[status])
  heading.append(name, mood)
  const voice = el('p', 'pet__voice', flashLine || pickVoiceLine({
    pools: messages.voice,
    status,
    hour: new Date(now).getHours(),
    seed: Math.floor(now / 60000),
  }))
  hero.append(heading, voice)

  const stats = el('div', 'stats')
  for (const key of ['fullness', 'energy', 'cleanliness'] as const) {
    const row = el('div', `stat stat--${key}${state.stats[key] < 30 ? ' stat--low' : ''}`)
    const label = el('span', 'stat__label', messages.stats[key])
    const value = el('strong', 'stat__value', String(state.stats[key]))
    const track = el('span', 'stat__track')
    const fill = el('span', 'stat__fill')
    fill.style.width = `${state.stats[key]}%`
    track.append(fill)
    row.append(label, value, track)
    stats.append(row)
  }

  const remaining = remainingCare(state, now)
  const actions = el('div', 'actions')
  for (const action of ACTIONS) {
    const button = el('button', 'action')
    button.type = 'button'
    button.disabled = remaining <= 0
    button.innerHTML = `<svg viewBox="0 0 32 32" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">${ACTION_ICONS[action]}</g></svg>`
    button.append(el('span', '', messages.actions[action].label))
    button.addEventListener('click', () => void care(action))
    actions.append(button)
  }

  const streak = getActiveStreak(state.streak, now)
  const meta = el('p', 'meta', remaining > 0
    ? messages.actionLimit.remaining.replace('{remaining}', String(remaining)).replace('{limit}', String(state.actionLimit.bonusUses + 10))
    : messages.actionLimit.locked)
  if (streak > 0) meta.append(el('span', 'meta__streak', messages.streak.days.replace('{days}', String(streak))))

  view.append(hero, stats, actions, meta, renderMore(state))

  return view
}

async function care(action: PetAction): Promise<void> {
  if (!pet) return

  const outcome = careFor(pet, action, Date.now())
  if (!outcome.ok) return

  pet = outcome.state
  flashLine = messages.careFeedback.done[action]
  if (flashTimer) clearTimeout(flashTimer)
  flashTimer = setTimeout(() => {
    flashLine = ''
    render()
  }, 2200)
  await save()
  render()
}

function renderMore(state: PetState): HTMLElement {
  const details = el('details', 'more')
  details.append(el('summary', '', messages.settings.settingsTab))

  const notify = el('label', 'toggle')
  const checkbox = el('input')
  checkbox.type = 'checkbox'
  void readStorage<boolean>(NOTIFY_KEY).then((value) => {
    checkbox.checked = value === true
  })
  checkbox.addEventListener('change', () => void writeStorage({ [NOTIFY_KEY]: checkbox.checked }))
  notify.append(checkbox, el('span', '', messages.notifications.toggle))

  const backupTitle = el('strong', 'more__title', messages.backup.heading)
  const backupHint = el('small', 'more__hint', messages.backup.description)
  const copy = el('button', 'ghost', messages.backup.copy)
  copy.type = 'button'
  copy.addEventListener('click', () => {
    void navigator.clipboard.writeText(encodePetBackup(state)).then(() => {
      copy.textContent = messages.backup.copied
    })
  })

  const input = el('textarea', 'code')
  input.rows = 2
  input.placeholder = messages.backup.placeholder
  const importButton = el('button', 'ghost', messages.backup.import)
  importButton.type = 'button'
  const notice = el('small', 'more__notice')
  importButton.addEventListener('click', () => {
    if (!input.value.trim() || !confirm(messages.backup.confirm)) return

    const backup = decodePetBackupWithPurchases(input.value, Date.now())
    if (!backup) {
      notice.textContent = messages.backup.invalid
      return
    }

    pet = { ...backup.state, lastUpdatedAt: Date.now() }
    void save().then(render)
  })

  details.append(notify, backupTitle, backupHint, copy, input, importButton, notice)

  return details
}

function renderAdoption(): HTMLElement {
  const view = el('div', 'adopt')
  view.append(el('strong', 'adopt__title', messages.setup.title), el('p', 'adopt__hint', messages.setup.description))

  const grid = el('div', 'adopt__grid')
  let chosen: PetSpecies = 'cat'
  const nameInput = el('input', 'adopt__name')
  nameInput.maxLength = 12
  nameInput.value = DEFAULT_PET_NAMES[chosen]

  for (const species of SPECIES) {
    const option = el('button', `adopt__option${species === chosen ? ' adopt__option--active' : ''}`)
    option.type = 'button'
    option.setAttribute('aria-label', messages.species[species].label)
    option.append(art(renderPetArtSvg({ species, status: 'happy', idPrefix: `adopt-${species}` }), 'adopt__art'))
    option.addEventListener('click', () => {
      chosen = species
      nameInput.value = DEFAULT_PET_NAMES[species]
      grid.querySelectorAll('.adopt__option').forEach((node) => node.classList.remove('adopt__option--active'))
      option.classList.add('adopt__option--active')
    })
    grid.append(option)
  }

  const start = el('button', 'primary', messages.setup.naming.start)
  start.type = 'button'
  start.addEventListener('click', () => {
    pet = adoptPet(chosen, nameInput.value.trim() || DEFAULT_PET_NAMES[chosen], Date.now())
    void save().then(render)
  })

  const moveHint = el('small', 'adopt__move', messages.backup.description)
  view.append(grid, nameInput, start, moveHint, renderImportOnly())

  return view
}

function renderImportOnly(): HTMLElement {
  const details = el('details', 'more')
  details.append(el('summary', '', messages.backup.heading))
  const input = el('textarea', 'code')
  input.rows = 2
  input.placeholder = messages.backup.placeholder
  const button = el('button', 'ghost', messages.backup.import)
  button.type = 'button'
  const notice = el('small', 'more__notice')
  button.addEventListener('click', () => {
    const backup = decodePetBackupWithPurchases(input.value, Date.now())
    if (!backup) {
      notice.textContent = messages.backup.invalid
      return
    }

    pet = { ...backup.state, lastUpdatedAt: Date.now() }
    void save().then(render)
  })
  details.append(input, button, notice)

  return details
}
